services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/favicon.ico :/var/www/laraapp/favicon.ico
      - ./backend/robots.txt:/var/www/laraapp/robots.txt
    depends_on:
      - php
    networks:
      - lara-app
  php:
    build:
      context: ./
      dockerfile: ./images/php/Dockerfile
    container_name: php
    working_dir: /var/www/laraapp
    volumes:
      - ./backend/:/var/www/laraapp
    ports:
      - "9000:9000"
#    environment:
#      - DB_CONNECTION="mysql"
#      - DB_HOST=localhost
#      - DB_DATABASE="laraapp"
#      - DB_PASSWORD="secret"
    depends_on:
      - mysql
    networks:
      - lara-app
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laraapp
    volumes:
      - lara-app-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - lara-app
volumes:
  lara-app-data:
networks:
  lara-app: